ai:
  platform:
    openai:
      api_key: '%env(OPENAI_API_KEY)%'
    gemini:
      api_key: '%env(GEMINI_API_KEY)%'
  agent:
    customer_support:
      platform: 'ai.platform.gemini'
      model: 'gemini-2.5-flash'
      prompt:
        text: 'Jesteś asystentem sklepu internetowego. Pomagaj użytkownikom sprawdzać status ich zamówień.'
        include_tools: true
      tools:
        - 'Boozt\Tools\OrderTrackingTool'
    wikipedia:
      platform: 'ai.platform.openai'
      model:
        name: 'gpt-4o-mini'
        options:
          temperature: 0.5
      prompt:
        text: 'Please answer the users question based on Wikipedia, only use information provided in the messages.'
        include_tools: true
      tools:
        - 'Symfony\AI\Agent\Bridge\Wikipedia\Wikipedia'
      include_sources: true
    pleo_support:
      platform: 'ai.platform.gemini'
      model: 'gemini-2.5-flash'
      prompt:
        text: 'Please answer the users question based on PLEO Export API, only use information provided in the messages.'
        include_tools: true
      tools:
        - 'Boozt\Tools\PleoExportTool'
